on:
  pull_request:
  push:
    branches:
      - tests

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://hawkingrei/tind:v5.1.1
        name: __all__
        with:
          args: |
            bash -c "pwd && ls && cat /etc/os-release && tox -e lint"
  tests:
    strategy:
      fail-fast: true
      matrix:
        pythonVersion:
          - 'py39'
        tidbVersion:
          - 'v4.0.15'
          - 'v5.0.3'
          - 'v5.1.1'
          - 'v5.2.1'
    name: test_${{ matrix.pythonVersion }}_tidb_${{ matrix.tidbVersion }}
    runs-on: ubuntu-latest
    container:
      image: hawkingrei/tind:${{ matrix.tidbVersion }}
    steps:
      - uses: actions/checkout@v3
      - name: start tidb
        run: service supervisor start && sleep 10s
      - name: init db
        run: mycli -P 4000  -h 127.0.0.1  -u root --execute='create database test_sqlalchemy;create database test_schema;'
      - name: run test
        run: tox -e ${{ matrix.pythonVersion }}
